name: Auto-update resources.json

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '0 2 * * 1'  # weekly update on Monday 02:00 UTC

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update JSON
        run: |
          node src/py/update-resources.js

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add resources.json
          git commit -m "Auto-updated resources.json"
          git push
